/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlidesRouteImport } from './routes/slides'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as FeatureCardsRouteImport } from './routes/feature-cards'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlidesIndexRouteImport } from './routes/slides.index'
import { Route as ComponentsIndexRouteImport } from './routes/components.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SlidesSlugRouteImport } from './routes/slides.$slug'
import { Route as ComponentsSlugRouteImport } from './routes/components.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SlidesRoute = SlidesRouteImport.update({
  id: '/slides',
  path: '/slides',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const FeatureCardsRoute = FeatureCardsRouteImport.update({
  id: '/feature-cards',
  path: '/feature-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlidesIndexRoute = SlidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlidesRoute,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComponentsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const SlidesSlugRoute = SlidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SlidesRoute,
} as any)
const ComponentsSlugRoute = ComponentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ComponentsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/components': typeof ComponentsRouteWithChildren
  '/feature-cards': typeof FeatureCardsRoute
  '/preview': typeof PreviewRoute
  '/slides': typeof SlidesRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/slides/$slug': typeof SlidesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/slides/': typeof SlidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feature-cards': typeof FeatureCardsRoute
  '/preview': typeof PreviewRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/slides/$slug': typeof SlidesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/slides': typeof SlidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/components': typeof ComponentsRouteWithChildren
  '/feature-cards': typeof FeatureCardsRoute
  '/preview': typeof PreviewRoute
  '/slides': typeof SlidesRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/slides/$slug': typeof SlidesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/slides/': typeof SlidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/components'
    | '/feature-cards'
    | '/preview'
    | '/slides'
    | '/blog/$slug'
    | '/components/$slug'
    | '/slides/$slug'
    | '/blog/'
    | '/components/'
    | '/slides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feature-cards'
    | '/preview'
    | '/blog/$slug'
    | '/components/$slug'
    | '/slides/$slug'
    | '/blog'
    | '/components'
    | '/slides'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/components'
    | '/feature-cards'
    | '/preview'
    | '/slides'
    | '/blog/$slug'
    | '/components/$slug'
    | '/slides/$slug'
    | '/blog/'
    | '/components/'
    | '/slides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  ComponentsRoute: typeof ComponentsRouteWithChildren
  FeatureCardsRoute: typeof FeatureCardsRoute
  PreviewRoute: typeof PreviewRoute
  SlidesRoute: typeof SlidesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/slides': {
      id: '/slides'
      path: '/slides'
      fullPath: '/slides'
      preLoaderRoute: typeof SlidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feature-cards': {
      id: '/feature-cards'
      path: '/feature-cards'
      fullPath: '/feature-cards'
      preLoaderRoute: typeof FeatureCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slides/': {
      id: '/slides/'
      path: '/'
      fullPath: '/slides/'
      preLoaderRoute: typeof SlidesIndexRouteImport
      parentRoute: typeof SlidesRoute
    }
    '/components/': {
      id: '/components/'
      path: '/'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/slides/$slug': {
      id: '/slides/$slug'
      path: '/$slug'
      fullPath: '/slides/$slug'
      preLoaderRoute: typeof SlidesSlugRouteImport
      parentRoute: typeof SlidesRoute
    }
    '/components/$slug': {
      id: '/components/$slug'
      path: '/$slug'
      fullPath: '/components/$slug'
      preLoaderRoute: typeof ComponentsSlugRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ComponentsRouteChildren {
  ComponentsSlugRoute: typeof ComponentsSlugRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

const ComponentsRouteChildren: ComponentsRouteChildren = {
  ComponentsSlugRoute: ComponentsSlugRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
}

const ComponentsRouteWithChildren = ComponentsRoute._addFileChildren(
  ComponentsRouteChildren,
)

interface SlidesRouteChildren {
  SlidesSlugRoute: typeof SlidesSlugRoute
  SlidesIndexRoute: typeof SlidesIndexRoute
}

const SlidesRouteChildren: SlidesRouteChildren = {
  SlidesSlugRoute: SlidesSlugRoute,
  SlidesIndexRoute: SlidesIndexRoute,
}

const SlidesRouteWithChildren =
  SlidesRoute._addFileChildren(SlidesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  ComponentsRoute: ComponentsRouteWithChildren,
  FeatureCardsRoute: FeatureCardsRoute,
  PreviewRoute: PreviewRoute,
  SlidesRoute: SlidesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
